### PR TITLE
Topics/support option list

### PR DESCRIPTION
**Pull request by sashless**
Be able to use an array for replacements

for https://github.com/Va1/string-replace-loader/pull/1#issuecomment-161956486

### CODE REVIEW

**Comment by sergeylaptev** [comment]
Btw i think this way is much better
for single option
```js
{
  search: 'string',
  replace: 'value',
}
```
for multiple values
```js
{
  multiple: [
    {
      search: 'string',
      replace: 'value',
    },
    {
      search: 'string2',
      replace: 'value2',
    },
  ],
}
```
The code will look like this:
```js
var utils = require('loader-utils');

function processQuery(source, query) {
  source = source.split(query.search).join(query.replace);
}

module.exports = function(source) {
  this.cacheable();

  var query = utils.parseQuery(this.query);

  if (Array.isArray(query.multiple)) {
    query.multiple.forEach(function(query) {
      processQuery(source, query);
    });
  } else if (typeof query.search !== 'undefined' && typeof query.replace !== 'undefined') {
    processQuery(source, query);
  }

  return source;
};
```

**Comment by sashless** [comment]
hm `much better` because using forEach and a different key ? I would call that just a different approach ;D According to https://jsperf.com/for-vs-foreach/75 `forEach` is even slower than for loop =)

**Comment by sashless** [comment]
Oh and your proposal is missing support for regex + flags which would break backward. I prefer to leave this as it is =)

**Comment by sergeylaptev** [comment]
I said "much better" not for performance, but for structure with/without "multiple" property:)

**Comment by sashless** [comment]
ah yea okay. This leads me to another thought. Why not doing a regex replacement and in addition array replacement ? Will use your idea with multiple key to do that

**Comment by sashless** [comment]
ah well nope, dont have enough time to tinker here so long =) will leave it as it is

**Comment by sergeylaptev** [comment]
String#split supports regex as argument, I think we don't need "flag" option anymore:) And here is 1.0.0 release:D

**Comment by sashless** [comment]
ah yea good point !

**Comment by sergeylaptev** [comment]
And here is the winner;)
```js
var utils = require('loader-utils');

function processQuery(source, query) {
  if (typeof query.search !== 'undefined' && typeof query.replace !== 'undefined') {
    source = source.split(query.search).join(query.replace);
  }
}

module.exports = function(source) {
  this.cacheable();

  var query = utils.parseQuery(this.query);

  if (Array.isArray(query.multiple)) {
    for (var i = 0; i < query.multiple.length; i++) {
      processQuery(source, query.multiple[i]);
    }
  } else {
    processQuery(source, query);
  }

  return source;
};
```

**Comment by sashless** [comment]
ah okay, i did it a bit different but basically the same. I think you have a bug inside your proposal anyway. Afaik source is a string and not passed by reference so you need to return it from processQuery.

**Comment by sergeylaptev** [comment]
Oops you're right! I write this code in Github, and didn't test it at all. Fixed last proposal

**Comment by sashless** [comment]
no worries. I didnt test it as well but looks good to me. We will see what @Va1 is saying =)

**Comment by sergeylaptev** [comment]
Just fixed last bug in processQuery in cases when condition of query properties isn't valid

**Comment by sashless** [comment]
yea i have seen that as well and already fixed that in my commit  https://github.com/easybiblabs/string-replace-loader/commit/adef248908916da6a57be2434a9789759dcb9358 :+1:

**Comment by sergeylaptev** [comment]
Good job, the solution is little bit different but main idea is the same:)

**Comment by sashless** [comment]
yup, i prefer to to return instead of else when possible. Thanks for collaboration =)

**Comment by Va1** [comment]
Hey, guys!

This all looks fine, I do love the idea of a better interface multiple replacement, I wander why did not I add this feature before. 

Though, I am feeling like using `source.split(query.search).join(query.replace);` is not really cool, because [String.prototype.replace()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace) is kinda designed for such operations (+ it supports function as a replacement).

So, I will merge this now, then apply some fixes, then bump the npm version. Will let you know by posting a message here.

Thanks a lot,
Val

**Comment by sergeylaptev** [comment]
@Va1 You are welcome;)

**Comment by sashless** [comment]
oh man sorry, didnt see there are tests available. I would have adjusted them otherwise :/  Thanks for merging !

**Comment by Va1** [comment]
OK, so. The reason of having `flags` options and using `new RegExp(...)` was the fact that webpack seems to be unable to pass a regular expression from a configuration code code to the actual loader code (due to some transformations to string and back on query parsing, I guess). So, when you define a `search` query option as a RegExp instance, it appears to be `{}` (empty object) when it comes to replacement. That's why I went with passing it as string and using `new RegExp(...)` with flags there. So now I am force to get back to this solution, while keeping multiple support of course. I wish I bethought of this ugly feature earlier, because I was wandering why test fail for 20 minutes or so.

**Comment by Va1** [comment]
Done!

**Comment by sashless** [comment]
nice thanks ! What a pitty that you added lodash again just to check for undefined and array. Can you please remove lodash again ? Those checks are easily done with vanilly js  :)

**Pull request merged**
