### PR TITLE
support replacement callbacks

### LINKED ISSUE #40: Feature request: callbacks
Would be great if I could specify a callback function as a replacement like:

```js
module.exports = {
  // ...
  module: {
    rules: [
      {
        test: /\.js$/,
        loader: 'string-replace-loader',
        options: {
          search: 'my name',
          replace: function(result){
                  return result.toUpperCase();
          },
          flags: 'gi'
        }
      }
    ]
  }
}
```

### PR DESCRIPTION
**Pull request by lightpohl**
Hello!

A little new to this, but this is a continuation of the discussion in #41.  I was able to get the tests running, and I added a simple test to show that it works and doesn't affect the other tests.

Credit to @balping for the code changes. 👏 

Let me know if I need to change anything!

P.S. Thanks for putting a module like this together. 😺 

fixes #40

### CODE REVIEW

**Comment by balping** [comment]
:+1: 

How do you run `npm test`? I still get

```
Uncaught AssertionError: expected [Error: ENOENT: no such file or directory, open '/tmp/string-replace-loader/test/build/build.js'] to equal null
```

**Comment by lightpohl** [comment]
Not quite sure what issue you're running into. Might be an environment problem? 

These are the steps I followed to run the tests initially: 
1. `git clone https://github.com/lightpohl/string-replace-loader.git`
2. `cd string-replace-loader`
3. `npm install`
4. `npm run test`

**Comment by balping** [comment]
I used yarn before, now I used npm and it works. I have no clue why the test doesn't work with yarn.

**Comment by itmayziii** [comment]
Can we please get this merged, the original PR in #41 has been open since march. I would be happy to help in any way if there is something blocking. 

Thank you for the library!

**Comment by gitgrimbo** [comment]
Hi, can this change be released?

**Comment by lightpohl** [comment]
For those who are interested, I went ahead and [published the forked version with support for replacement callbacks to NPM under my scope](https://www.npmjs.com/package/@lightpohl/string-replace-loader). Feel free to use it until the feature is available officially.

**Comment by lightpohl** [comment]
Hello! Just a quick FYI: going to close down this PR due to inactivity. I'll leave the forked version up on npm, but I've marked it as deprecated.

**Comment by Va1** [comment]
supported as of 2.2.0. thanks everyone

**Pull request closed without merging**
