### PR TITLE
can pass an array of search & replace options

### PR DESCRIPTION
**Pull request by sashless**

### CODE REVIEW

**Comment by sergeylaptev** [comment]
Why this PR has been closed? I think we need support array of replacements

**Comment by sashless** [comment]
Hmm good question. I closed it because I used the
create

wrong base for my pull request. I merged into my fork to prevent waiting
and arguing about my PR because I just wanted to use array replacement.

I will create another PR :+1:

sergeylaptev <notifications@github.com> schrieb am Fr., 4. Dez. 2015 13:16:

**Comment by sergeylaptev** [comment]
@sashless Ok, still waiting it, or maybe I'll add this feature in my fork too:D

**Comment by sashless** [comment]
hehe =) PR comes in a minute

**Pull request closed without merging**
